import { Notification, NotificationType, NotificationStatus } from './types';

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    title: 'Settlement Completed',
    message: 'Settlement batch #BATCH-2024-001 has been successfully processed.',
    type: NotificationType.SUCCESS,
    status: NotificationStatus.READ,
    timestamp: '2024-05-20T14:30:00Z',
    actionUrl: '/settlements/batch-2024-001',
    actionText: 'View Details',
  },
  {
    id: '2',
    title: 'High Risk Transaction Detected',
    message: 'Transaction TXN-89234 flagged for review. Risk score: 85/100',
    type: NotificationType.SECURITY,
    status: NotificationStatus.UNREAD,
    timestamp: '2024-05-20T13:15:00Z',
    actionUrl: '/transactions/txn-89234',
    actionText: 'Review',
  },
  {
    id: '3',
    title: 'KYC Verification Pending',
    message: 'Customer CUST-1002 requires KYC review. 3 documents submitted.',
    type: NotificationType.VERIFICATION,
    status: NotificationStatus.UNREAD,
    timestamp: '2024-05-20T12:45:00Z',
    actionUrl: '/customers/cust-1002',
    actionText: 'Review',
  },
  {
    id: '4',
    title: 'API Integration Degraded',
    message: 'Bank of China API response time increased by 300%.',
    type: NotificationType.WARNING,
    status: NotificationStatus.READ,
    timestamp: '2024-05-20T11:20:00Z',
  },
  {
    id: '5',
    title: 'Scheduled Maintenance',
    message: 'System maintenance scheduled for May 21, 2024 from 02:00-04:00 UTC.',
    type: NotificationType.SYSTEM,
    status: NotificationStatus.READ,
    timestamp: '2024-05-20T10:00:00Z',
  },
  {
    id: '6',
    title: 'New Merchant Registration',
    message: 'Merchant "Global Tech Solutions" has completed registration.',
    type: NotificationType.INFO,
    status: NotificationStatus.UNREAD,
    timestamp: '2024-05-20T09:30:00Z',
    actionUrl: '/merchants/m-1009',
  },
  {
    id: '7',
    title: 'Failed Transaction',
    message: 'Transaction TXN-89235 failed due to insufficient funds.',
    type: NotificationType.ERROR,
    status: NotificationStatus.UNREAD,
    timestamp: '2024-05-20T08:45:00Z',
    actionUrl: '/transactions/txn-89235',
  },
];